import type { Locales } from "../constants";

export * from "./application-command";
export * from "./application-role-connection-metadata";
export * from "./application";
export * from "./audit-log";
export * from "./auto-moderation";
export * from "./channel";
export * from "./emoji";
export * from "./entitlements";
export * from "./gateway-events";
export * from "./guild-scheduled-event";
export * from "./guild-template";
export * from "./guild";
export * from "./interaction";
export * from "./invite";
export * from "./message-components";
export * from "./role";
export * from "./sku";
export * from "./stage-instance";
export * from "./sticker";
export * from "./team";
export * from "./user";
export * from "./voice";
export * from "./webhook";
export type LocaleMap = Partial<Record<Locales, string>>;
